
const translations = {
  en: {
    greetings: 'Hello, I am Dermocracy Bot!',
    mainMenu: 'Main menu',
    option1: 'Option 1',
    option2: 'Option 2',
    option3: 'Option 3',
    questionsList: 'Here are the questions for voting:',
    submitQuestion: 'Please submit your question for voting:',
    statistics: 'Here are the voting statistics:',
    unknownOption: "Sorry, I didn't understand that option.",
    submitQuestionInstructions: 'Type your question below and press Enter:',
    sampleQuestion1: 'Should we create a new channel for memes?',
    sampleQuestion2: 'Should we have a weekly meeting?',
    voteQuestion: 'Do you vote YES or NO for the question:',
    votingResults: 'Voting results:',
    yes: 'Yes',
    no: 'No',
	statsText: 'Total chats: {totalChats}\nTotal users: {totalUsers}\nTotal votes: {totalVotes}',
    candidate_registration_success: 'You have successfully registered as a candidate.',
    candidate_registration_error: 'Error while registering candidate.',
    election_started: 'Election has started.',
    election_start_error: 'Error while starting the election.',
    president_impeachment_started: 'Impeachment process has started.',
    president_impeachment_error: 'Error while starting the impeachment process.',
    president_impeachment_success: 'The president has been successfully impeached.',
    president_impeachment_failure: 'The impeachment process has failed.',
    impeachment_not_allowed: 'Only the president can initiate the impeachment process.',
    impeachment_voting_ongoing: 'Impeachment voting is ongoing. Please wait for the results.',
	  
  },
  ru: {
    greetings: 'Привет, я Dermocracy Bot!',
    mainMenu: 'Главное меню',
    option1: 'Опция 1',
    option2: 'Опция 2',
    option3: 'Опция 3',
    questionsList: 'Вот список вопросов для голосования:',
    submitQuestion: 'Пожалуйста, предложите вопрос для голосования:',
    statistics: 'Вот статистика голосования:',
    unknownOption: 'Извините, я не понимаю эту опцию.',
    submitQuestionInstructions: 'Введите ваш вопрос ниже и нажмите Enter:',
    sampleQuestion1: 'Создать ли новый канал для мемов?',
    sampleQuestion2: 'Проводить ли еженедельные встречи?',
    voteQuestion: 'Голосуете ли вы ЗА или ПРОТИВ вопроса:',
    votingResults: 'Результаты голосования:',
    yes: 'За',
    no: 'Против',
	statsText: 'Всего чатов: {totalChats}\nВсего пользователей: {totalUsers}\nВсего голосов: {totalVotes}'
    candidate_registration_success: 'Вы успешно зарегистрировались в качестве кандидата.',
    candidate_registration_error: 'Ошибка при регистрации кандидата.',
    election_started: 'Выборы начались.',
    election_start_error: 'Ошибка при начале выборов.',
    president_impeachment_started: 'Процесс импичмента начался.',
    president_impeachment_error: 'Ошибка при начале процесса импичмента.',
    president_impeachment_success: 'Президент успешно импичментирован.',
    president_impeachment_failure: 'Процесс импичмента не удался.',
    impeachment_not_allowed: 'Только президент может начать процесс импичмента.',
    impeachment_voting_ongoing: 'Голосование по импичменту продолжается. Пожалуйста, дождитесь результатов.',
   
  }
};
module.exports = translations;
